kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-response-engine-cluster-role
rules:
  - apiGroups:
    - ""
    resources:
      - pods
    verbs:
      - delete
      - list
      - patch
  - apiGroups:
    - ""
    resources:
      - nodes
    verbs:
      - patch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
