apiVersion: v1
kind: Service
metadata:
  name: "example-app-{{ .Values.tag }}"
  namespace: development
  labels:
    app.kubernetes.io/name: "example-app-{{ .Values.tag }}"
    helm.sh/chart: {{ include "example-application.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
   - port: 8080
  selector:
    app.kubernetes.io/name: "example-app-{{ .Values.tag }}"
    app.kubernetes.io/instance: {{ .Release.Name }}