apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "example-app-{{ .Values.tag }}"
  namespace: development
  labels:
    app.kubernetes.io/name: "example-app-{{ .Values.tag }}"
    helm.sh/chart: {{ include "example-application.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: "example-app-{{ .Values.tag }}"
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "example-app-{{ .Values.tag }}"
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: example-app
          image: example-app:latest
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 128Mi


