apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-response-engine-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-response-engine-cluster-role
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: kubernetes-response-engine
