apiVersion: v1
appVersion: 0.5.0
description: Anchore container analysis and policy evaluation engine service
engine: gotpl
home: https://anchore.com
icon: https://anchore.com/wp-content/uploads/2016/08/anchore.png
keywords:
- analysis
- docker
- anchore
- anchore-engine
- image
- security
- vulnerability
- scanner
maintainers:
- email: zach@anchore.com
  name: zhill
- email: bradyt@anchore.com
  name: btodhunter
name: anchore-engine
sources:
- https://github.com/anchore/anchore-engine
version: 1.3.2
